package com.realestate.agent.util;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.realestate.agent.entity.DueDiligenceReport;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Component
public class PdfGenerator {

    public byte[] generatePdf(DueDiligenceReport report) {

        try {

            Document document = new Document();

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            PdfWriter.getInstance(document, outputStream);

            document.open();

            document.add(new Paragraph("DUE DILIGENCE REPORT"));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Report ID : " + report.getReportId()));
            document.add(new Paragraph("Property : " + report.getProperty().getPropertyName()));
            document.add(new Paragraph("Generated By : " + report.getGeneratedBy().getEmail()));
            document.add(new Paragraph("Risk Score : " + report.getOverallRiskScore()));
            document.add(new Paragraph("Status : " + report.getReportStatus()));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Executive Summary"));
            document.add(new Paragraph(report.getExecutiveSummary()));

            document.close();

            return outputStream.toByteArray();

        } catch (DocumentException e) {
            throw new RuntimeException("Failed to generate PDF.", e);
        }
    }
}