package com.realestate.agent.controller;

import com.realestate.agent.dto.DueDiligenceReportRequest;
import com.realestate.agent.dto.DueDiligenceReportResponse;
import com.realestate.agent.security.CustomUserDetails;
import com.realestate.agent.service.ReportService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

import java.util.List;

@RestController
@RequestMapping("/api/reports")
@SecurityRequirement(name = "bearerAuth")
@Tag(name = "Report Controller", description = "CRUD APIs for Managing Due Diligence Reports")
public class DueDiligenceReportController {

    private final ReportService reportService;

    public DueDiligenceReportController(ReportService reportService) {
        this.reportService = reportService;
    }

    @PostMapping
    @PreAuthorize("hasAnyRole('ADMINISTRATOR', 'LEGAL_REVIEWER', 'REAL_ESTATE_AGENT', 'BUYER', 'FINANCIAL_INSTITUTION')")
    @Operation(summary = "Generate a due diligence report", description = "Generates a new property due diligence report for the authenticated user.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Report created successfully",
                    content = @Content(schema = @Schema(implementation = DueDiligenceReportResponse.class))),
            @ApiResponse(responseCode = "400", description = "Invalid request payload"),
            @ApiResponse(responseCode = "404", description = "Property or User not found")
    })
    public ResponseEntity<DueDiligenceReportResponse> generateReport(
            @Valid @RequestBody DueDiligenceReportRequest request,
            @AuthenticationPrincipal CustomUserDetails userDetails
    ) {
        DueDiligenceReportResponse response = reportService.generateReport(request, userDetails.getUsername());
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get report by ID", description = "Retrieves details of a specific report by ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Report details retrieved",
                    content = @Content(schema = @Schema(implementation = DueDiligenceReportResponse.class))),
            @ApiResponse(responseCode = "404", description = "Report not found")
    })
    public ResponseEntity<DueDiligenceReportResponse> getReportById(@PathVariable("id") Long id) {
        DueDiligenceReportResponse response = reportService.getReportById(id);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/property/{propertyId}")
    @Operation(summary = "Get reports for a property", description = "Lists all reports associated with a specific property ID.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Reports list retrieved"),
            @ApiResponse(responseCode = "404", description = "Property not found")
    })
    public ResponseEntity<List<DueDiligenceReportResponse>> getReportsByProperty(@PathVariable("propertyId") Long propertyId) {
        List<DueDiligenceReportResponse> response = reportService.getReportsByProperty(propertyId);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/my")
    @Operation(summary = "Get reports generated by authenticated user", description = "Lists all reports generated by the currently logged-in user.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "User reports retrieved")
    })
    public ResponseEntity<List<DueDiligenceReportResponse>> getMyReports(
            @AuthenticationPrincipal CustomUserDetails userDetails
    ) {
        List<DueDiligenceReportResponse> response = reportService.getMyReports(userDetails.getUserId());
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMINISTRATOR', 'LEGAL_REVIEWER', 'REAL_ESTATE_AGENT')")
    @Operation(summary = "Update report details", description = "Updates details of an existing report. Only Administrators, Legal Reviewers, and Real Estate Agents can perform this action.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Report updated successfully",
                    content = @Content(schema = @Schema(implementation = DueDiligenceReportResponse.class))),
            @ApiResponse(responseCode = "404", description = "Report or Property not found")
    })
    public ResponseEntity<DueDiligenceReportResponse> updateReport(
            @PathVariable("id") Long id,
            @Valid @RequestBody DueDiligenceReportRequest request
    ) {
        DueDiligenceReportResponse response = reportService.updateReport(id, request);
        return ResponseEntity.ok(response);
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMINISTRATOR', 'LEGAL_REVIEWER', 'REAL_ESTATE_AGENT')")
    @Operation(summary = "Delete report", description = "Deletes a report by ID. Only Administrators, Legal Reviewers, and Real Estate Agents can perform this action.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Report deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Report not found")
    })
    public ResponseEntity<Void> deleteReport(@PathVariable("id") Long id) {
        reportService.deleteReport(id);
        return ResponseEntity.noContent().build();
    }

    @GetMapping("/{id}/pdf")
    @Operation(summary = "Export report as PDF")
    public ResponseEntity<byte[]> exportPdf(@PathVariable("id") Long id) {

        byte[] pdf = reportService.exportPdf(id);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=Due_Diligence_Report_" + id + ".pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdf);
    }

    @GetMapping("/{id}/excel")
    @Operation(summary = "Export report as Excel")
    public ResponseEntity<byte[]> exportExcel(@PathVariable("id") Long id) {

        byte[] excel = reportService.exportExcel(id);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=Due_Diligence_Report_" + id + ".xlsx")
                .contentType(MediaType.parseMediaType(
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))
                .body(excel);
    }
}
